<x-guest-layout>
    <div class="mb-8"><p class="heritage-label">Buat ruangmu</p><h1 class="mt-2 text-3xl font-semibold">Mulai dengan tenang.</h1><p class="mt-3 text-sm leading-6" style="color: var(--heritage-muted)">Demo only. Gunakan data dummy dan jangan upload KTP asli.</p></div>
    <form method="POST" action="{{ route('register') }}" enctype="multipart/form-data" class="space-y-5">@csrf
        <div><x-input-label for="name" value="Nama" /><x-text-input id="name" class="mt-2 block w-full" type="text" name="name" :value="old('name')" required autofocus autocomplete="name" /><x-input-error :messages="$errors->get('name')" class="mt-2" /></div>
        <div><x-input-label for="email" value="Email" /><x-text-input id="email" class="mt-2 block w-full" type="email" name="email" :value="old('email')" required autocomplete="username" /><x-input-error :messages="$errors->get('email')" class="mt-2" /></div>
        <div><x-input-label for="tradition_id" value="Agama" /><select id="tradition_id" name="tradition_id" class="mt-2 block min-h-11 w-full border-gray-400" required><option value="">Pilih Agama</option>@foreach ($traditions as $tradition)<option value="{{ $tradition->id }}" @selected(old('tradition_id') == $tradition->id)>{{ $tradition->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('tradition_id')" class="mt-2" /></div>
        <div><x-input-label for="proof_file" value="Foto bukti dummy" /><input id="proof_file" class="mt-2 block w-full text-sm" type="file" name="proof_file" accept="image/jpeg,image/png" required /><x-input-error :messages="$errors->get('proof_file')" class="mt-2" /></div>
        <label for="consent" class="flex items-start gap-2 text-sm"><input id="consent" type="checkbox" name="consent" value="1" required @checked(old('consent'))><span>Saya setuju memakai data dummy untuk demo.</span></label><x-input-error :messages="$errors->get('consent')" class="mt-2" />
        <div><x-input-label for="password" value="Kata sandi" /><x-text-input id="password" class="mt-2 block w-full" type="password" name="password" required autocomplete="new-password" /><x-input-error :messages="$errors->get('password')" class="mt-2" /></div>
        <div><x-input-label for="password_confirmation" value="Ulangi kata sandi" /><x-text-input id="password_confirmation" class="mt-2 block w-full" type="password" name="password_confirmation" required autocomplete="new-password" /><x-input-error :messages="$errors->get('password_confirmation')" class="mt-2" /></div>
        <div class="flex flex-wrap items-center justify-between gap-4 pt-2"><a class="text-sm font-semibold underline" href="{{ route('login') }}">Sudah punya akun?</a><button class="heritage-button-primary">Daftar</button></div>
    </form>
</x-guest-layout>
