<x-app-layout>
    <x-slot name="header"><p class="heritage-label">Konten</p><h1 class="mt-2 text-3xl font-semibold">Kelola rencana bacaan</h1></x-slot>
    <div class="heritage-container space-y-6 py-10">
        @if (session('status')) <p class="border border-green-700 bg-green-50 p-3 text-sm text-green-900">{{ session('status') }}</p> @endif
        <form method="POST" action="{{ route('admin.reading-plans.store') }}" class="heritage-surface space-y-4 p-6">@csrf<input name="title" required class="block min-h-11 w-full border-gray-400" placeholder="Judul"><textarea name="description" class="block min-h-24 w-full border-gray-400" placeholder="Deskripsi"></textarea><input name="source" required class="block min-h-11 w-full border-gray-400" placeholder="Sumber"><div class="grid gap-2 sm:grid-cols-2"><input name="items[0][title]" required class="min-h-11 border-gray-400" placeholder="Hari 1"><input name="items[0][reference]" required class="min-h-11 border-gray-400" placeholder="Rujukan"></div><button class="heritage-button-primary">Tambah rencana</button></form>
        @foreach ($plans as $plan)<article class="heritage-surface space-y-4 p-6"><form method="POST" action="{{ route('admin.reading-plans.update', $plan) }}" class="space-y-3">@csrf @method('PATCH')<input name="title" value="{{ $plan->title }}" required class="block min-h-11 w-full border-gray-400"><textarea name="description" class="block min-h-20 w-full border-gray-400">{{ $plan->description }}</textarea><input name="source" value="{{ $plan->source }}" required class="block min-h-11 w-full border-gray-400"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked($plan->is_active)> Aktif</label><div class="flex flex-wrap gap-2"><button class="heritage-button-secondary">Simpan perubahan</button></form><form method="POST" action="{{ route('admin.reading-plans.destroy', $plan) }}">@csrf @method('DELETE')<button class="heritage-button-secondary">Hapus</button></form></div></article>@endforeach
        {{ $plans->links() }}
    </div>
</x-app-layout>
