<x-app-layout>
    <x-slot name="header"><p class="heritage-label">Konten</p><h1 class="mt-2 text-3xl font-semibold">Kelola kutipan</h1></x-slot>
    <div class="heritage-container space-y-6 py-10">
        @if (session('status')) <p class="border border-green-700 bg-green-50 p-3 text-sm text-green-900">{{ session('status') }}</p> @endif
        <form method="POST" action="{{ route('admin.quotes.store') }}" class="heritage-surface space-y-4 p-6">@csrf<textarea name="body" required class="block min-h-28 w-full border-gray-400" placeholder="Isi kutipan"></textarea><input name="source" required class="block min-h-11 w-full border-gray-400" placeholder="Sumber"><input type="date" name="scheduled_for" class="min-h-11 border-gray-400"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" checked> Aktif</label><button class="heritage-button-primary">Tambah kutipan</button></form>
        @foreach ($quotes as $quote)<article class="heritage-surface space-y-4 p-6"><form method="POST" action="{{ route('admin.quotes.update', $quote) }}" class="space-y-3">@csrf @method('PATCH')<textarea name="body" required class="block min-h-24 w-full border-gray-400">{{ $quote->body }}</textarea><input name="source" value="{{ $quote->source }}" required class="block min-h-11 w-full border-gray-400"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked($quote->is_active)> Aktif</label><div class="flex flex-wrap gap-2"><button class="heritage-button-secondary">Simpan perubahan</button></form><form method="POST" action="{{ route('admin.quotes.publish', $quote) }}">@csrf<button class="heritage-button-secondary">{{ $quote->is_active ? 'Sembunyikan' : 'Terbitkan' }}</button></form><form method="POST" action="{{ route('admin.quotes.destroy', $quote) }}">@csrf @method('DELETE')<button class="heritage-button-secondary">Hapus</button></form></div></article>@endforeach
        {{ $quotes->links() }}
    </div>
</x-app-layout>
